version: "2"

services:
  sigfox-mqtt-bridge:
    build:
      context: .
    image: campusiot/sigfox-mqtt-bridge:latest
#    links:
#      - mqtt-1:moquitto
    ports:
      - 8080:8080
    volumes:
      - ~/configuration/sigfox-mqtt-bridge/settings.json:/usr/src/app/settings.json:ro
#      - ~/configuration/sigfox-mqtt-bridge/htpasswd:/usr/src/app/htpasswd:ro
    restart: unless-stopped
